### ISSUE TITLE
use of uninitialized value $result

### ISSUE THREAD

**Issue by ACH1980** [t0k4rt/IDPSSO_X509_fingerprint#3]
I've downloaded your script but when I try to execute it, the following happened:

`root@git:~/workdesk/IDPSSO_X509_fingerprint# ./x509_fingerprint.sh ~/workdesk/saml-sp-metadata.xml
Use of uninitialized value $result in division (/) at ./x509_pem_extractor.pl line 28, <$fh> line 11.
Use of uninitialized value $result in substr at ./x509_pem_extractor.pl line 30, <$fh> line 11.
unable to load certificate
root@git:~/workdesk/IDPSSO_X509_fingerprint#`

**Comment by t0k4rt** [comment]
Are you sure you are using a valid IDPSSO certificate ?
(there should be a `<dsig:X509Certificate></dsig:X509Certificate>` section in your certificate)
Also, it's only tested on perl 5.18
How do you call the script ?

**Comment by ACH1980** [comment]
How I call this script is in the snippet above. I've only the saml-sp-metadata.xml 

This file could be found here:
https://git.kanjias.de/root/blub/blob/master/saml-sp-metadata.xml

It looks like the part that you mentioned is not in this file.

I followed this tutorial where it's referenced to this repository in step 3:
https://edenmal.moe/post/2018/GitLab-Keycloak-SAML-2-0-OmniAuth-Provider/

What can I do to solve this problem?

**Comment by ACH1980** [comment]
It looks like I've found an XML file that contains the appropriate section. Will test and if it works I'll close the issue.

**Comment by ACH1980** [comment]
It works. Thanks for helping.
